name: Go package

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: master
  #push:
   # branches:    
    #  - 'feature-**'
     # - 'bug-*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: go test
        
      #- name: Create Pull Request
      #  uses: peter-evans/create-pull-request@v4
      #  with:
      #    base: 'master'

      - name: Build
        run: go build
